### ISSUE TITLE
Check if search name is available

### ISSUE THREAD

**Issue by dccoder84** [evilpie/add-custom-search-engine#31]
I wondered why I cannot add eBay as a search engine. Turns out the name was already used internally some way even if I hadn't installed an eBay search. So "ebay" instead of "eBay" as search name worked but it would be nice if the user could get some type of feedback otherwise this is quite confusing. Tested with Firefox 84.0.2.

**Comment by evilpie** [comment]
Good idea. I think we should be able to do this with [search.get](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/search/get). So far I have resisted doing this because it requires adding a new permission.

**Comment by dccoder84** [comment]
If you need inspiration how to code this you can have a look at how Firefox itself implemented it. The GUI has to be enabled and is behing a flag under about:config. You have to set the variable browser.urlbar.update2.engineAliasRefresh to true then you will see an additional "Add" button add the bottom of about:preferences#search. If you click this button you will get a dialogue which is similar to you addon. The "add search enginge" button within the dialogue will grey out if the search engine name is already available. The best thing would be if somebody provides a patch so that this dialogue will also have an option to set an icon. Then your addon wouldn't be that important anymore. Of course your addon still has more options and would still be useful d-(' ' d-).

**Comment by dccoder84** [comment]
Cool, thank you very much :)

**Comment by dccoder84** [comment]
Sorry but it doesn't work correctly. I can still type "eBay" without getting a feedback. And in the URL-Bar-Three-Dots-Dropdown-Menu there won't be an entry "Add Search Engine" then.

**Comment by evilpie** [comment]
@dccoder84 Is it possible that you have that search engine installed but hidden? i.e. no blue in about:preferences#search.

**Comment by dccoder84** [comment]
I don't know what's the problem but everything works fine when using a fresh profile and a new Firefox installation.

**Comment by akwala** [comment]
I was able to add a custom search engine for _ebay.com_ by doing the following:

1. Remove "eBay" from the search engines at `about:preferences#search`.
2. Quit and relaunch Firefox.
3. Use this extension to add the custom search engine, naming it "eBay.com".

When I tried adding the custom search engine immediately after removing the predefined listing in Settings, I got the following error regardless of the name I used:

> Firefox could not install the search plugin from “https://dpaste.org/Hy8Bf/raw” because an engine with the same name already exists.

Note, however, that Firefox doesn't allow setting `@ebay` as the keyword of this custom search engine, apparently because it's hardcoded for the predefined one.
