### ISSUE TITLE
Firefox Proton removes all page actions including "Add search engine"

### ISSUE THREAD

**Issue by Redfire75369** [evilpie/add-custom-search-engine#33]
Following the steps on the add search engine page, I am unable to add the search engine as there is no "Add Search Engine" option.
![](https://imgur.com/5Vks2eU.png)

Environment:
Windows 10 10.0.18363 Build 18363
Firefox Developer Edition 88.0b6

**Comment by evilpie** [comment]
Still works for me in Nightly. Can you tell me the settings you used?

**Comment by Redfire75369** [comment]
I did some testing because I had a slight suspicion it was caused by the Proton redesign.
The option `browser.proton.urlbar.enabled=true` resulted in the "Add Search Engine" option disappearing.

**Comment by allanlaal** [comment]
the `Page Actions` menu has been removed from the URLbar/awesomebar since Firefox ≥ 89.0b3 (Proton UI :vomiting_face: ) 

setting `browser.proton.enabled = false` disabled the UI "improvements" and brought that menu back

in the new Puketon.. I mean Proton: one has to Right Click on the urlbar and the `Add Search Engine` option appears there on first load

**Comment by allanlaal** [comment]
@Redfire75369 @evilpie could you edit this issue title to `FIX "Add Search Engine" and its "Page Actions"/.../meatball menu missing in Firefox Proton (≥v89)`

**Comment by evilpie** [comment]
Thanks for reminding me. Having to right click is somewhat annoying to visualize :(

**Comment by evilpie** [comment]
Right clicking the address bar didn't work? It's working for me with proton enabled.

**Comment by titaniumbones** [comment]
proton is enabled and the ight click menu looks as followed when clicked from (a) the extension "create new engine" page, and (b) a normal page, in this case on researchgate.
![research-gate-page-r-click](https://user-images.githubusercontent.com/364340/117990327-10a20d80-b30b-11eb-8b3f-5c9c937902f4.png)
![extension-page-r-clickmenu](https://user-images.githubusercontent.com/364340/117990332-113aa400-b30b-11eb-8939-8953b61dc9b9.png)

thanks for the quick response!

**Comment by evilpie** [comment]
Weird, do you see anything in the browser console? (Ctrl+Shift+J)

**Comment by leijurv** [comment]
This UI change appears to have been rolled out globally or something. I just got it and I'm not on any beta (that I know of).



I believe the issue is that adding the link element in JavaScript is no longer sufficient.

I performed the above test with researchgate, and I saw the same behavior. `Add "ResearchGate search"` appeared on that page, but nothing appeared on your extension.

I copied the two link elements into a local .html file. If I put in `<link rel="search" type="application/opensearchdescription+xml" title="r" href="https://paste.mozilla.org/9EiMJrKP/raw">` (copied from the inspect element view), it worked fine and showed up. Same for `<link rel="search" type="application/opensearchdescription+xml" title="ResearchGate search" href="https://www.researchgate.net/application.DownloadOpenSearchPlugin.html">`.

I suspect/fear that Firefox changed something up internally, and now `<link rel="search"` only works if it is in the HTML on initial page load, and it won't show up if it's added later using JavaScript.

**Comment by evilpie** [comment]
Still works fine for me, just have to right click. I am going to update the help text and screenshots tomorrow or so.

**Comment by evilpie** [comment]
If you reproduce this reliably it would be useful if you could take a look at the browser console (Ctrl+Shift+J)

**Comment by evilpie** [comment]
Released version 4.1: https://addons.mozilla.org/firefox/addon/add-custom-search-engine/ (https://github.com/evilpie/add-custom-search-engine/commit/8210107bb72cb1be0462ecf5bfe519ddc602f00e)

**Comment by leijurv** [comment]
Huh... I can't reproduce this anymore. I might have just been doing something wrong earlier today. Or some cache issue. Or your update. 

Regardless, all seems well now, no issue anymore (at least for me) :) 👍

**Comment by codepincher** [comment]
I am still having this issue...I've found the https://paste.mozilla.org link but have no idea how to add it. Nor do I know how to add the functionality for the custom search back to firefox.
